#!/bin/bash

test_bin="./test"

if [ ! -f "$test_bin" ]; then
    echo "Test binary not found. Please run 'make test' first."
    exit 1
fi

failed_tests=0

function run_test {
    local test_name="$1"
    local expected_rc="$2"
    local slurm_job_partition="$3"
    local spank_context="$4"
    local config_string="$5"

    echo "[TEST: $test_name, expect rc = $expected_rc]"
    # Run test and compare return code to expected
    if [ -n "$slurm_job_partition" ]; then
        export SLURM_JOB_PARTITION="$slurm_job_partition"
    fi
    export SPANK_CONTEXT="$spank_context"

    output=$(./test $config_string 2>&1)
    local actual_rc="$?"
    if [ "$actual_rc" -eq "$expected_rc" ]; then
        echo "Pass"
    else
        echo "Log:"
        echo "++++"
        echo $output
        echo "++++"
        echo "FAIL: $test_name (expected rc: $expected_rc, actual rc: $actual_rc)"
        echo
        failed_tests=$((failed_tests + 1))
    fi
    echo
    unset SLURM_JOB_PARTITION
    unset SPANK_CONTEXT
}

# Create a fake netns for testing. We won't actually use it, but we just need it to exist and be openable for the tests.
touch /tmp/testns

run_test "Missing config" 1 "testpart" 1 "partition=testpart"

run_test "Unknown config" 2 "testpart" 1 "partition=testpart netns=/tmp/testns UNKNOWN_OPTION=value"

run_test "Not remote context" 3 "testpart" 0 "partition=testpart netns=/tmp/testns"

run_test "Missing SLURM_JOB_PARTITION" 4 "" 1 "partition=testpart netns=/tmp/testns"

run_test "Wrong SLURM_JOB_PARTITION" 5 "wrongpart" 1 "partition=testpart netns=/tmp/testns"

run_test "Missing netns" 6 "testpart" 1 "partition=testpart netns=/tmp/nonexistent"

# Use a symlink to trigger test fail
ln -s /tmp/testns /tmp/testns.link
run_test "Unopenable netns" 7 "testpart" 1 "partition=testpart netns=/tmp/testns.link"
rm /tmp/testns.link

# Change ownership to trigger test fail
chown nobody /tmp/testns
run_test "Netns path not owned by root" 8 "testpart" 1 "partition=testpart netns=/tmp/testns"
chown root /tmp/testns

run_test "setns() fail" 9 "testpart" 1 "partition=testpart netns=/tmp/testns"

# Cleanup
rm /tmp/testns

echo "---------------------------------"
echo "Total failed tests: $failed_tests"
echo "---------------------------------"

exit $failed_tests
