name: Build and Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libslurm-dev

      - name: Build
        run: make

      - name: Clean
        run: make clean

      - name: Build test
        run: make test

      - name: Run tests
        run: |
          set +e
          set -u

          test_bin="./test"

          failed_tests=0

          function run_test {
              local test_name="$1"
              local expected_rc="$2"
              local slurm_job_partition="$3"
              local spank_context="$4"
              local config_string="$5"

              echo "[TEST: $test_name, expect rc = $expected_rc]"
              # Run test and compare return code to expected
              if [ -n "$slurm_job_partition" ]; then
                  export SLURM_JOB_PARTITION="$slurm_job_partition"
              fi
              export SPANK_CONTEXT="$spank_context"

              output=$(sudo --preserve-env=SLURM_JOB_PARTITION,SPANK_CONTEXT ./test $config_string 2>&1)
              local actual_rc="$?"

              if [ "$actual_rc" -eq "$expected_rc" ]; then
                  echo "Pass"
              else
                  echo "Log:"
                  if [ -n "$output" ]; then
                      echo "++++"
                      echo "$output"
                      echo "++++"
                  else
                      echo "(no output)"
                  fi
                  echo "FAIL: $test_name (expected rc: $expected_rc, actual rc: $actual_rc)"
                  echo ""
                  failed_tests=$((failed_tests + 1))
              fi

              echo ""

              unset SLURM_JOB_PARTITION
              unset SPANK_CONTEXT
          }

          # -----------------------------------------------------
          # Setup:
          NSNAME=testns
          NETS_FAKE_ROOT="/tmp/${NSNAME}"
          NETS_FAKE_NONROOT="/tmp/${NSNAME}_nonroot"
          NETS_REAL_ROOT="/var/run/netns/${NSNAME}"
          NETNS_SYMLINK="/var/run/netns/${NSNAME}.link"

          # Set up fake network namespaces (both owned by root and non-root)
          sudo touch $NETS_FAKE_ROOT $NETS_FAKE_NONROOT
          sudo chown nobody $NETS_FAKE_NONROOT

          # Set up a real network namespace
          sudo ip netns add $NSNAME

          # Create symlink as a "bad" netns
          sudo ln -s $NETS_REAL_ROOT $NETNS_SYMLINK

          # -----------------------------------------------------

          run_test "end-to-end"                   0 "testpart"  1 "partition=testpart netns=$NETS_REAL_ROOT"
          run_test "Missing config"               1 "testpart"  1 "partition=testpart"
          run_test "Unknown config"               2 "testpart"  1 "partition=testpart netns=$NETS_REAL_ROOT UNKNOWN_OPTION=value"
          run_test "Not remote context"           3 "testpart"  0 "partition=testpart netns=$NETS_REAL_ROOT"
          run_test "Missing SLURM_JOB_PARTITION"  4 ""          1 "partition=testpart netns=$NETS_REAL_ROOT"
          run_test "Wrong SLURM_JOB_PARTITION"    5 "wrongpart" 1 "partition=testpart netns=$NETS_REAL_ROOT"
          run_test "Missing netns"                6 "testpart"  1 "partition=testpart netns=/tmp/nonexistent"
          run_test "Unopenable netns"             7 "testpart"  1 "partition=testpart netns=$NETNS_SYMLINK"
          run_test "Netns path not owned by root" 8 "testpart"  1 "partition=testpart netns=$NETS_FAKE_NONROOT"
          run_test "setns() fail"                 9 "testpart"  1 "partition=testpart netns=$NETS_FAKE_ROOT"

          # Cleanup
          sudo ip netns delete $NSNAME

          echo "---------------------------------"
          echo "Total failed tests: $failed_tests"
          echo "---------------------------------"

          exit $failed_tests
