name: Build and Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libslurm-dev

      - name: Build
        run: make

      - name: Clean
        run: make clean

      - name: Build test
        run: make test

      - name: Run tests
        run: |
          set -u

          failed_tests=0

          function run_test {
              set +e
              local test_name="$1"
              local expected_rc="$2"
              local slurm_job_partition="$3"
              local spank_context="$4"
              local config_string="$5"

              echo "[TEST: $test_name, expect rc = $expected_rc]"
              # Run test and compare return code to expected
              if [ -n "$slurm_job_partition" ]; then
                  export SLURM_JOB_PARTITION="$slurm_job_partition"
              fi
              export SPANK_CONTEXT="$spank_context"

              output=$(sudo --preserve-env=SLURM_JOB_PARTITION,SPANK_CONTEXT ./test $config_string 2>&1)
              local actual_rc="$?"

              if [ "$actual_rc" -eq "$expected_rc" ]; then
                  echo "Pass"
              else
                  echo "Log:"
                  if [ -n "$output" ]; then
                      echo "++++"
                      echo "$output"
                      echo "++++"
                  else
                      echo "(no output)"
                  fi
                  echo "FAIL: $test_name (expected rc: $expected_rc, actual rc: $actual_rc)"
                  echo ""
                  failed_tests=$((failed_tests + 1))
              fi

              echo ""

              unset SLURM_JOB_PARTITION
              unset SPANK_CONTEXT
              set -e
          }

          # -----------------------------------------------------
          # Setup:

          # Set up a real network namespace
          sudo ip netns add test

          # Set up fake 'network namespace' files
          sudo touch /tmp/test
          touch /tmp/ns_nonroot && sudo chown nobody /tmp/ns_nonroot
          sudo ln -s /var/run/netns/test /var/run/netns/test.link

          # Create directory usable for pinning mount-namespaces, and create an empty mount point
          sudo mkdir -p /run/mntns
          sudo mount --make-rslave --bind /run/mntns /run/mntns
          sudo touch /run/mntns/test

          # Ensure there is a non-existent path for testing missing netns
          sudo rm -f /tmp/nonexistent

          # Enter our pre-created netns using 'ip netns exec', which sets up a temporary mount namespace and mounts things from /etc/netns/, and remounts /sys.
          # Then escape that mount namespace, and enter the parent mount namespace instead.
          # Finally, use a bind mount to pin the temporary mount namespace created by 'ip', to make it persistent.
          # Note: we must have 'bash -c' trigger a fork() here, so the command is intentionally not "simple", to prevent optimisation. i.e. multiple commands, (where ':' is the POSIX null utility).
          sudo ip netns exec test bash -c "nsenter --mount -t $$ mount --bind /proc/\$\$/ns/mnt /run/mntns/test && :"

          # -----------------------------------------------------

          run_test "end-to-end"                   0 "testpart"  1 "partition=testpart netns=/var/run/netns/test      mntns=/run/mntns/test"
          run_test "Missing config"               1 "testpart"  1 "partition=testpart"
          run_test "Unknown config"               2 "testpart"  1 "partition=testpart netns=/var/run/netns/test      mntns=/run/mntns/test UNKNOWN_OPTION=value"
          run_test "Not remote context"           3 "testpart"  0 "partition=testpart netns=/var/run/netns/test      mntns=/run/mntns/test"
          run_test "Missing SLURM_JOB_PARTITION"  4 ""          1 "partition=testpart netns=/var/run/netns/test      mntns=/run/mntns/test"
          run_test "Wrong SLURM_JOB_PARTITION"    5 "wrongpart" 1 "partition=testpart netns=/var/run/netns/test      mntns=/run/mntns/test"
          run_test "Missing netns"                6 "testpart"  1 "partition=testpart netns=/tmp/nonexistent         mntns=/run/mntns/test"
          run_test "Unopenable netns"             7 "testpart"  1 "partition=testpart netns=/var/run/netns/test.link mntns=/run/mntns/test"
          run_test "Netns path not owned by root" 8 "testpart"  1 "partition=testpart netns=/tmp/ns_nonroot          mntns=/run/mntns/test"
          run_test "setns() fail"                 9 "testpart"  1 "partition=testpart netns=/tmp/test                mntns=/run/mntns/test"

          # Cleanup
          sudo ip netns delete test
          sudo umount /run/mntns/test
          sudo umount /run/mntns
          sudo rm -rf /run/mntns

          echo "---------------------------------"
          echo "Total failed tests: $failed_tests"
          echo "---------------------------------"

          exit $failed_tests
